In [1]:
import pandas as pd
import numpy as np

In [2]:
# check pandas version
print(pd.__version__)

2.1.4

In [5]:
file_path = r"C:\Users\chhat\Computer_Code\Dummy_Data\movies1.csv"

In [6]:
df = pd.read_csv(file_path, encoding='unicode_escape')

In [ ]:
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime
0,Blood Red Sky,2021,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri Baume...,21062,121
1,Masters of the Universe: Revelation,2021,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michelle Gellar, Lena ...",17870,25
2,The Walking Dead,2010,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman Reedus, Melissa M...",885805,44
3,Rick and Morty,2013,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Parnell, Spencer G...",414849,23
4,Outer Banks,2020,"Action, Crime, Drama",7.6,A group of teenagers from the wrong side of th...,"Stars:Chase Stokes, Madelyn Cline, Madison Bai...",25858,50
...,...,...,...,...,...,...,...,...
6526,Sexify,2021,"Comedy, Drama",6.8,"Monika's idea for gathering data is a hit, but...",Director:Kalina Alabrudzinska| Stars:Aleks...,108,38
6527,Sexify,2021,"Comedy, Drama",7.1,After facing their parents at Easter breakfast...,Director:Kalina Alabrudzinska| Stars:Aleks...,103,37
6528,Sexify,2021,"Comedy, Drama",6.9,After getting an anonymous tip about the copul...,Director:Kalina Alabrudzinska| Stars:Aleks...,96,40
6529,Sexify,2021,"Comedy, Drama",7.1,The big pitch at the university tech competiti...,Director:Kalina Alabrudzinska| Stars:Aleks...,100,47
6530,Castlevania,2017,"Animation, Action, Adventure",8.2,Lenore urges Hector to not test Camilla's pati...,Director:Sam Deats| Stars:Richard Armitage...,911,24

In [ ]:
df.head(0) # shows the only columns name in your data

df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime
0,Blood Red Sky,2021,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri Baume...,21062,121
1,Masters of the Universe: Revelation,2021,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michelle Gellar, Lena ...",17870,25
2,The Walking Dead,2010,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman Reedus, Melissa M...",885805,44
3,Rick and Morty,2013,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Parnell, Spencer G...",414849,23
4,Outer Banks,2020,"Action, Crime, Drama",7.6,A group of teenagers from the wrong side of th...,"Stars:Chase Stokes, Madelyn Cline, Madison Bai...",25858,50

In [ ]:
df.tail()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime
6526,Sexify,2021,"Comedy, Drama",6.8,"Monika's idea for gathering data is a hit, but...",Director:Kalina Alabrudzinska| Stars:Aleks...,108,38
6527,Sexify,2021,"Comedy, Drama",7.1,After facing their parents at Easter breakfast...,Director:Kalina Alabrudzinska| Stars:Aleks...,103,37
6528,Sexify,2021,"Comedy, Drama",6.9,After getting an anonymous tip about the copul...,Director:Kalina Alabrudzinska| Stars:Aleks...,96,40
6529,Sexify,2021,"Comedy, Drama",7.1,The big pitch at the university tech competiti...,Director:Kalina Alabrudzinska| Stars:Aleks...,100,47
6530,Castlevania,2017,"Animation, Action, Adventure",8.2,Lenore urges Hector to not test Camilla's pati...,Director:Sam Deats| Stars:Richard Armitage...,911,24

In [ ]:
df.columns

Index(['MOVIES', 'YEAR', 'GENRE', 'RATING', 'ONE-LINE', 'STARS', 'VOTES',
       'RunTime'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=6531, step=1)

In [ ]:
df.value_counts()

MOVIES                                                       YEAR  GENRE                            RATING  ONE-LINE                                                                                                                                                                                                                       STARS                                                                                                                 VOTES  RunTime
#AnneFrank - Parallel Stories                                2019  Drama, History                   6.5     It is based on five women who did survive the Holocaust but shared her same fate of "deportation, suffering and being denied their childhood and adolescence," according to promotional materials.                             Directors:Sabina Fedeli, Anna Migotto|     Stars:Helen Mirren, Anne Frank, Martina Gatti, Arianna Szorenyi            1296   92         1
Rock My Heart                                                2017  Drama                            6.5     17-year-old Jana has a congenital heart defect. To defy fate, Jana seeks every challenge, plunges into every wild and dangerous adventure. Her parents do not like that and are even more in constant fear of their daughter.  Director:Hanno Olderdissen|     Stars:Emilio Sakraya, Lena Klenke, Dieter Hallervorden, Milan Peschel                 864    105        1
Rolling Thunder Revue: A Bob Dylan Story by Martin Scorsese  2019  Documentary, Biography, History  7.6     In an alchemic mix of fact and fantasy, Martin Scorsese looks back at Bob Dylan's 1975 Rolling Thunder Revue tour and a country ripe for reinvention.                                                                          Director:Martin Scorsese|     Stars:Bob Dylan, Allen Ginsberg, Patti Smith, Martin von Haselberg                      5987   142        1
Roll with Me                                                 2017  Documentary                      8.3     After hitting rock-bottom, a newly sober paraplegic attempts to save his gang-banger nephew's life by bringing him along on a 3,100-mile wheelchair trek across the United States.                                             Director:Lisa France|     Stars:Gabriel Cordell, Christopher Kawas, Lisa France, J.A. Streeter                        82     90         1
Roll Red Roll                                                2018  Documentary, Crime               7.1     An account of a notable sexual assault that took place in Steubenville, Ohio in 2012, and the role that social media played in the crime and on the community.                                                                 Director:Nancy Schwartzman|     Stars:Mark Cole, Anthony Craig, Rachel Dissell, Alexandria Goddard                    2377   80         1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ..
Gojira: KaijÃ» Wakusei                                        2017  Animation, Action, Adventure     6.0     A desperate group of refugees attempts to recolonize Earth 20,000 years after Godzilla took over, but one young man wants revenge above all else.                                                                              Directors:Hiroyuki Seshita, KÃ´bun Shizuno|     Stars:Mamoru Miyano, Takahiro Sakurai, Kana Hanazawa, Tomokazu Sugita  8108   89         1
Gojira shingyura pointo                                      2021  Animation, Action, Adventure     7.3     Mei learns of a large explosion triggered by Ashihara's calculator long ago. Kanoko gives Matsubara the Orthogonal Diagonalizer to use against Godzilla.                                                                       Directors:Nao Miyoshi, Noriyuki Nomata, Takuma Suzuki|     Star:Cristina Valenzuela                                   50     24         1
                                                                                                    7.1     Mei, BB and Pelops II attempt to prevent the Catastrophe, but Salunga ambushes them. Meanwhile, the Otaki crew make their final push toward Godzilla.                                                                          Directors:Takuma Suzuki, Atsushi Takahashi                                                                            55     24         1
                                                                                                    7.0     Before heading to the Super Dimension Calculator, BB offers Mei a view of the Singular Point. The Otaki crew leave for Tokyo to destroy Godzilla.                                                                              Director:Takuma Suzuki|     Star:Cristina Valenzuela                                                                  47     24         1
ÃœberWeihnachten                                              2020  Comedy, Drama, Romance           7.5     Sausages and Potato Salad - Basti hooks up with his brother's ex. The stolen Christmas tree is revealed by an angry Vicar as is the "off" behavior of his parents when Bastian discovers a big secret.                         Stars:Luke Mockridge, Seyneb Saleh, Cristina do Rego, Lucas Reiber                                                    66     50         1
Name: count, Length: 6495, dtype: int64

In [ ]:
df.values

array([['Blood Red Sky', 2021, 'Action, Horror, Thriller', ...,
        'Director:Peter Thorwarth|     Stars:Peri Baumeister, Carl Anton Koch, Alexander Scheer, Kais Setti',
        21062, 121],
       ['Masters of the Universe: Revelation', 2021,
        'Animation, Action, Adventure', ...,
        'Stars:Chris Wood, Sarah Michelle Gellar, Lena Headey, Mark Hamill',
        17870, 25],
       ['The Walking Dead', 2010, 'Drama, Horror, Thriller', ...,
        'Stars:Andrew Lincoln, Norman Reedus, Melissa McBride, Lauren Cohan',
        885805, 44],
       ...,
       ['Sexify', 2021, 'Comedy, Drama', ...,
        'Director:Kalina Alabrudzinska|     Stars:Aleksandra Skraba, Maria Sobocinska, Sandra Drzymalska, Piotr Pacek',
        96, 40],
       ['Sexify', 2021, 'Comedy, Drama', ...,
        'Director:Kalina Alabrudzinska|     Stars:Aleksandra Skraba, Maria Sobocinska, Sandra Drzymalska, Piotr Pacek',
        100, 47],
       ['Castlevania', 2017, 'Animation, Action, Adventure', ...,
        'Director:Sam Deats|     Stars:Richard Armitage, James Callis, Alejandra Reynoso, Jessica Brown Findlay',
        911, 24]], dtype=object)

In [ ]:
df.describe()

              YEAR       RATING         VOTES      RunTime
count  6531.000000  6531.000000  6.531000e+03  6531.000000
mean   2015.241004     6.893294  1.749290e+04    68.427653
std       8.210633     1.239319  7.602795e+04    47.567630
min    1932.000000     1.100000  5.000000e+00     1.000000
25%    2014.000000     6.200000  2.795000e+02    35.000000
50%    2018.000000     7.100000  1.188000e+03    60.000000
75%    2019.000000     7.800000  4.859000e+03    94.000000
max    2021.000000     9.900000  1.713028e+06   853.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6531 entries, 0 to 6530
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    6531 non-null   object
 1   YEAR      6531 non-null   int32
 2   GENRE     6524 non-null   object
 3   RATING    6531 non-null   float64
 4   ONE-LINE  6531 non-null   object
 5   STARS     6502 non-null   object
 6   VOTES     6531 non-null   int64
 7   RunTime   6531 non-null   int64
dtypes: float64(1), int32(1), int64(2), object(4)
memory usage: 382.8+ KB

In [8]:
# to change the datatype of YEAR column form int64 to int32

df['YEAR']=df['YEAR'].astype('int32')

In [ ]:
df.shape

(6531, 8)

In [ ]:
df.size

52248

In [ ]:
df.isnull().sum()

MOVIES       0
YEAR         0
GENRE        7
RATING       0
ONE-LINE     0
STARS       29
VOTES        0
RunTime      0
dtype: int64

In [ ]:
df.isnull().sum().sum() # it shows the total number of NAN in your dataset

36

In [ ]:
round(df.isna().sum().sum() / df.size * 100, 1) #to shows the total % of null values in your dataset

0.1

In [ ]:
df[df.duplicated()]  # check duplicated rows

Empty DataFrame
Columns: [MOVIES, YEAR, GENRE, RATING, ONE-LINE, STARS, VOTES, RunTime]
Index: []

In [ ]:
df = df.dropna(subset=['GENRE'])   #it remove the NA value from "GENRE" column

In [ ]:
# to delete the unwanted column, 1 for columns and 0 for rows

#df= df.drop("Gross", axis=1)

In [ ]:
#df.to_string()

In [ ]:
# df= pd.set_option("display.max_columns", 20)
# print(df)

In [ ]:
rows = df.sample(frac=.0002)  # this shows the 0.0002% of data of df

In [ ]:
# find unique values in rows or columns

df.nunique(axis=1, dropna=True)

df.nunique(axis=0, dropna=True)

MOVIES      4726
YEAR          76
GENRE        456
RATING        82
ONE-LINE    6373
STARS       5690
VOTES       3883
RunTime      259
dtype: int64

In [ ]:
# pd.set_option("display.max_columns", 15)
# pd.set_option("display.max_rows", 15)

In [ ]:
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime
0,Blood Red Sky,2021,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri Baume...,21062,121
1,Masters of the Universe: Revelation,2021,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michelle Gellar, Lena ...",17870,25
2,The Walking Dead,2010,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman Reedus, Melissa M...",885805,44
3,Rick and Morty,2013,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Parnell, Spencer G...",414849,23
4,Outer Banks,2020,"Action, Crime, Drama",7.6,A group of teenagers from the wrong side of th...,"Stars:Chase Stokes, Madelyn Cline, Madison Bai...",25858,50
...,...,...,...,...,...,...,...,...
6526,Sexify,2021,"Comedy, Drama",6.8,"Monika's idea for gathering data is a hit, but...",Director:Kalina Alabrudzinska| Stars:Aleks...,108,38
6527,Sexify,2021,"Comedy, Drama",7.1,After facing their parents at Easter breakfast...,Director:Kalina Alabrudzinska| Stars:Aleks...,103,37
6528,Sexify,2021,"Comedy, Drama",6.9,After getting an anonymous tip about the copul...,Director:Kalina Alabrudzinska| Stars:Aleks...,96,40
6529,Sexify,2021,"Comedy, Drama",7.1,The big pitch at the university tech competiti...,Director:Kalina Alabrudzinska| Stars:Aleks...,100,47
6530,Castlevania,2017,"Animation, Action, Adventure",8.2,Lenore urges Hector to not test Camilla's pati...,Director:Sam Deats| Stars:Richard Armitage...,911,24

In [ ]:
df.isnull().sum()

MOVIES       0
YEAR         0
GENRE        0
RATING       0
ONE-LINE     0
STARS       29
VOTES        0
RunTime      0
dtype: int64

In [ ]:
df.isnull().sum().sum()  # to show the total null value of your dataset

29

In [ ]:
df.filter(items=["MainBranch", "Hobbyist"], axis=1)  #to filter out the columns


df.filter(items=[5], axis=0) # to filter out rows on basis of index number

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime
5,The Last Letter from Your Lover,2021,"Drama, Romance",6.8,A pair of interwoven stories set in the past a...,Director:Augustine Frizzell| Stars:Shailen...,5283,110

In [ ]:
#df.filter(like="East Asian", axis=0)

In [ ]:
df.drop([2,3,4,5], axis=0) # drop the rows by using index

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime
0,Blood Red Sky,2021,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri Baume...,21062,121
1,Masters of the Universe: Revelation,2021,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michelle Gellar, Lena ...",17870,25
6,Dexter,2006,"Crime, Drama, Mystery",8.6,"By day, mild-mannered Dexter is a blood-spatte...","Stars:Michael C. Hall, Jennifer Carpenter, Dav...",665387,53
7,Never Have I Ever,2020,Comedy,7.9,The complicated life of a modern-day first gen...,"Stars:Maitreyi Ramakrishnan, Poorna Jagannatha...",34530,30
8,Virgin River,2019,"Drama, Romance",7.4,"Seeking a fresh start, nurse practitioner Meli...","Stars:Alexandra Breckenridge, Martin Henderson...",27279,44
...,...,...,...,...,...,...,...,...
6526,Sexify,2021,"Comedy, Drama",6.8,"Monika's idea for gathering data is a hit, but...",Director:Kalina Alabrudzinska| Stars:Aleks...,108,38
6527,Sexify,2021,"Comedy, Drama",7.1,After facing their parents at Easter breakfast...,Director:Kalina Alabrudzinska| Stars:Aleks...,103,37
6528,Sexify,2021,"Comedy, Drama",6.9,After getting an anonymous tip about the copul...,Director:Kalina Alabrudzinska| Stars:Aleks...,96,40
6529,Sexify,2021,"Comedy, Drama",7.1,The big pitch at the university tech competiti...,Director:Kalina Alabrudzinska| Stars:Aleks...,100,47
6530,Castlevania,2017,"Animation, Action, Adventure",8.2,Lenore urges Hector to not test Camilla's pati...,Director:Sam Deats| Stars:Richard Armitage...,911,24

In [ ]:
#df.drop(["MainBranch","Hobbyist"], inplace=True, axis=1)  # to drop any columns by using label or columns name, inplace use if u want to parmanent change in main data

In [ ]:
# use of loc and iloc

# loc for location or label based, and in slicing like 1:5, then 5 included in output data
# iloc for index based, and in slicing like 1:5, then 5 will be not included in output data

In [ ]:
df.fillna("ram")  # this method just fill all the data which have "NaN" with "ram"

df.dropna()  # just drop all the rows which have the NaN value, remaining rows will be shows.

df.isna() # or df.isnull() both are same, wherever the value NaN present it will shows True, otherwise False

      MOVIES   YEAR  GENRE  RATING  ONE-LINE  STARS  VOTES  RunTime
0      False  False  False   False     False  False  False    False
1      False  False  False   False     False  False  False    False
2      False  False  False   False     False  False  False    False
3      False  False  False   False     False  False  False    False
4      False  False  False   False     False  False  False    False
...      ...    ...    ...     ...       ...    ...    ...      ...
6526   False  False  False   False     False  False  False    False
6527   False  False  False   False     False  False  False    False
6528   False  False  False   False     False  False  False    False
6529   False  False  False   False     False  False  False    False
6530   False  False  False   False     False  False  False    False

[6524 rows x 8 columns]

In [ ]:
df.columns= [x.upper() for x in df.columns]

In [ ]:
df.columns = df.columns.str.replace(",", "_")

In [ ]:
# renaming columns

df.rename(columns = {"C":"A"})  # using rename function and pass the dict old value, new value

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RUNTIME
0,Blood Red Sky,2021,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri Baume...,21062,121
1,Masters of the Universe: Revelation,2021,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michelle Gellar, Lena ...",17870,25
2,The Walking Dead,2010,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman Reedus, Melissa M...",885805,44
3,Rick and Morty,2013,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Parnell, Spencer G...",414849,23
4,Outer Banks,2020,"Action, Crime, Drama",7.6,A group of teenagers from the wrong side of th...,"Stars:Chase Stokes, Madelyn Cline, Madison Bai...",25858,50
...,...,...,...,...,...,...,...,...
6526,Sexify,2021,"Comedy, Drama",6.8,"Monika's idea for gathering data is a hit, but...",Director:Kalina Alabrudzinska| Stars:Aleks...,108,38
6527,Sexify,2021,"Comedy, Drama",7.1,After facing their parents at Easter breakfast...,Director:Kalina Alabrudzinska| Stars:Aleks...,103,37
6528,Sexify,2021,"Comedy, Drama",6.9,After getting an anonymous tip about the copul...,Director:Kalina Alabrudzinska| Stars:Aleks...,96,40
6529,Sexify,2021,"Comedy, Drama",7.1,The big pitch at the university tech competiti...,Director:Kalina Alabrudzinska| Stars:Aleks...,100,47
6530,Castlevania,2017,"Animation, Action, Adventure",8.2,Lenore urges Hector to not test Camilla's pati...,Director:Sam Deats| Stars:Richard Armitage...,911,24

In [ ]:
# to clean all the data which have extra characters like -, \ / ... anthing which are not required

        # df['Last_Name'] = df['Last_Name'].str.lstrip('...')
        # df['Last_Name'] = df['Last_Name'].str.lstrip('/')
        # df['Last_Name'] = df['Last_Name'].str.rstrip('_')



            # OR to apply one single code for all
            
# df['Last_Name'].str.strip('123._/')

In [ ]:
df.STARS.isnull()

0       False
1       False
2       False
3       False
4       False
        ...
6526    False
6527    False
6528    False
6529    False
6530    False
Name: STARS, Length: 6524, dtype: bool

In [ ]:
df.STARS.isna()    #the method .isna or .isnull both are same and both work same, there is no difference

0       False
1       False
2       False
3       False
4       False
        ...
6526    False
6527    False
6528    False
6529    False
6530    False
Name: STARS, Length: 6524, dtype: bool

In [ ]:
df= df.dropna(subset=['STARS'])

In [ ]:
df['RATING'] = df['RATING'].round(1)

df

C:\Users\chhat\AppData\Local\Temp\ipykernel_9780\1226060847.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RATING'] = df['RATING'].round(1)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RUNTIME
0,Blood Red Sky,2021,"Action, Horror, Thriller",6.1,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri Baume...,21062,121
1,Masters of the Universe: Revelation,2021,"Animation, Action, Adventure",5.0,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michelle Gellar, Lena ...",17870,25
2,The Walking Dead,2010,"Drama, Horror, Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman Reedus, Melissa M...",885805,44
3,Rick and Morty,2013,"Animation, Adventure, Comedy",9.2,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Parnell, Spencer G...",414849,23
4,Outer Banks,2020,"Action, Crime, Drama",7.6,A group of teenagers from the wrong side of th...,"Stars:Chase Stokes, Madelyn Cline, Madison Bai...",25858,50
...,...,...,...,...,...,...,...,...
6526,Sexify,2021,"Comedy, Drama",6.8,"Monika's idea for gathering data is a hit, but...",Director:Kalina Alabrudzinska| Stars:Aleks...,108,38
6527,Sexify,2021,"Comedy, Drama",7.1,After facing their parents at Easter breakfast...,Director:Kalina Alabrudzinska| Stars:Aleks...,103,37
6528,Sexify,2021,"Comedy, Drama",6.9,After getting an anonymous tip about the copul...,Director:Kalina Alabrudzinska| Stars:Aleks...,96,40
6529,Sexify,2021,"Comedy, Drama",7.1,The big pitch at the university tech competiti...,Director:Kalina Alabrudzinska| Stars:Aleks...,100,47
6530,Castlevania,2017,"Animation, Action, Adventure",8.2,Lenore urges Hector to not test Camilla's pati...,Director:Sam Deats| Stars:Richard Armitage...,911,24

In [ ]:
pd.options.mode.chained_assignment = None  # this is for error removing command

In [ ]:
df['VOTES']= df['VOTES'].astype(float).astype(int, errors='ignore') #to convert datatype from float to int

In [ ]:
df = df.dropna(subset=['VOTES'])

In [ ]:
df.isnull().sum()

MOVIES      0
YEAR        0
GENRE       0
RATING      0
ONE-LINE    0
STARS       0
VOTES       0
RUNTIME     0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6495 entries, 0 to 6530
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    6495 non-null   object
 1   YEAR      6495 non-null   int64
 2   GENRE     6495 non-null   object
 3   RATING    6495 non-null   float64
 4   ONE-LINE  6495 non-null   object
 5   STARS     6495 non-null   object
 6   VOTES     6495 non-null   int32
 7   RUNTIME   6495 non-null   int64
dtypes: float64(1), int32(1), int64(2), object(4)
memory usage: 431.3+ KB

In [ ]:
df.YEAR

0       2021
1       2021
2       2010
3       2013
4       2020
        ...
6526    2021
6527    2021
6528    2021
6529    2021
6530    2017
Name: YEAR, Length: 6495, dtype: int64

In [ ]:
df.GENRE.unique()

array(['Action, Horror, Thriller', 'Animation, Action, Adventure',
       'Drama, Horror, Thriller', 'Animation, Adventure, Comedy',
       'Action, Crime, Drama', 'Drama, Romance', 'Crime, Drama, Mystery',
       'Comedy', 'Action, Adventure, Thriller', 'Crime, Drama, Fantasy',
       'Drama, Horror, Mystery', 'Crime, Drama, Thriller', 'Drama',
       'Comedy, Drama', 'Drama, Fantasy, Horror', 'Comedy, Romance',
       'Action, Adventure, Drama', 'Crime, Drama',
       'Drama, History, Romance', 'Horror, Mystery', 'Comedy, Crime',
       'Action, Drama, History', 'Comedy, Drama, Romance',
       'Action, Adventure, Fantasy', 'Action, Crime, Mystery',
       'Drama, Fantasy, Romance', 'Drama, Sci-Fi, Thriller',
       'Biography, Drama, History', 'Action, Crime, Horror',
       'Crime, Thriller', 'Comedy, Crime, Drama',
       'Drama, Mystery, Thriller', 'Action, Adventure, Mystery',
       'Action, Comedy', 'Crime, Drama, Horror', 'Drama, Mystery, Sci-Fi',
       'Action, Comedy, Crime', 'Action, Adventure, Crime',
       'Action, Adventure, Sci-Fi', 'Animation, Comedy',
       'Action, Comedy, Drama', 'Crime, Horror, Thriller',
       'Action, Adventure, Comedy', 'Animation, Comedy, Drama',
       'Adventure, Fantasy, Romance', 'Action, Drama, Fantasy',
       'Action, Adventure, Biography', 'Comedy, Drama, Fantasy',
       'Crime, Drama, Romance', 'Adventure, Thriller',
       'Biography, Crime, Drama', 'Documentary, Crime, Mystery',
       'Action, Drama, Horror', 'Action, Adventure',
       'Animation, Action, Fantasy', 'Comedy, Drama, Music',
       'Action, Crime, Sport', 'Action, Drama', 'Drama, Mystery, Romance',
       'Animation, Action, Comedy', 'Animation, Short, Comedy',
       'Thriller', 'Adventure, Fantasy', 'Action, Drama, Sci-Fi',
       'Game-Show, Reality-TV, Romance', 'Comedy, Crime, Thriller',
       'Musical, Romance', 'Documentary', 'Action, Drama, Mystery',
       'Action, Thriller', 'Animation, Crime, Drama', 'Adventure, Drama',
       'Animation, Adventure, Family', 'Animation, Action, Horror',
       'Drama, Fantasy', 'Drama, Thriller', 'Reality-TV, Romance',
       'Reality-TV', 'Adventure, Sci-Fi', 'Drama, Family',
       'Animation, Drama, Romance', 'Adventure, Comedy, Crime',
       'Comedy, Fantasy, Romance', 'Adventure, Drama, Family',
       'Action, Crime, Thriller', 'Biography, Drama, Sport',
       'Comedy, Family, Sci-Fi', 'Animation, Comedy, Romance',
       'Animation, Drama, Fantasy', 'Drama, Fantasy, Sci-Fi',
       'Adventure, Horror, Thriller', 'Action, Comedy, War',
       'Horror, Sci-Fi', 'Adventure, Drama, Horror', 'Drama, Western',
       'Drama, History, Thriller', 'Comedy, Drama, Western',
       'Drama, Music, Romance', 'Horror, Sci-Fi, Thriller',
       'Biography, Drama', 'Family, Fantasy, Musical',
       'Comedy, Crime, Romance', 'Comedy, Drama, Family',
       'Drama, Fantasy, Mystery', 'Comedy, Drama, Sport',
       'Crime, Drama, History', 'Drama, Family, Romance',
       'Adventure, Comedy, Drama', 'Game-Show, Reality-TV',
       'Documentary, Crime, History', 'Comedy, Drama, Musical',
       'Adventure, Drama, History', 'Adventure, Comedy, Reality-TV',
       'Action, Sci-Fi, Thriller', 'Family, Fantasy, Mystery',
       'Biography, Comedy', 'Comedy, Music', 'Adventure, Comedy, Romance',
       'Comedy, Drama, Sci-Fi', 'Comedy, Horror',
       'Biography, Comedy, Drama', 'Action, Biography, Drama',
       'Adventure, Drama, Mystery', 'Comedy, Musical',
       'Animation, Adventure, Drama', 'Comedy, Family', 'Drama, Horror',
       'Drama, Family, Fantasy', 'Action, Crime, Fantasy',
       'Animation, Action, Drama', 'Action, Fantasy, Mystery',
       'Action, Comedy, Horror', 'Adventure, Drama, Fantasy',
       'Action, Comedy, Family', 'Drama, History',
       'Action, Drama, Thriller', 'Documentary, Biography, History',
       'Short, Family', 'Adventure, Comedy, Fantasy',
       'Comedy, Reality-TV', 'Comedy, Drama, Thriller',
       'Action, Adventure, Family', 'Horror', 'Crime, Mystery, Sci-Fi',
       'Action, Comedy, Romance', 'Adventure, Biography, Drama',
       'Comedy, Sci-Fi', 'Drama, Romance, War',
       'Animation, Family, Fantasy', 'Adventure, Fantasy, Sci-Fi',
       'Crime, Horror, Mystery', 'Drama, Family, Sport',
       'Drama, Horror, Sci-Fi', 'Biography, Drama, Romance',
       'Action, Horror, Mystery', 'Horror, Thriller',
       'Drama, Family, Reality-TV', 'Comedy, Mystery',
       'Action, Romance, Thriller', 'Action, Crime, Sci-Fi',
       'Drama, Music, Musical', 'Documentary, Sport', 'Comedy, Sport',
       'Documentary, Biography, Drama', 'Comedy, Family, Romance',
       'Biography, Drama, Family', 'Horror, Mystery, Thriller',
       'Action, Horror, Sci-Fi', 'Animation, Drama, Music',
       'Comedy, Family, Music', 'Action, Comedy, Fantasy',
       'Adventure, Family, Fantasy', 'Mystery, Thriller', 'Action, Crime',
       'Adventure, Drama, War', 'Sci-Fi', 'Drama, History, Sport',
       'Drama, Music', 'Horror, Mystery, Sci-Fi', 'Drama, Sci-Fi',
       'Drama, War', 'Documentary, Biography, Crime',
       'Documentary, Biography, Sport', 'Animation, Adventure, Fantasy',
       'Action, Western', 'Adventure, Comedy, Family',
       'Action, Fantasy, Sci-Fi', 'Animation, Adventure',
       'Documentary, Crime', 'Drama, Horror, Music',
       'Action, Mystery, Thriller', 'Biography, Drama, Music',
       'Drama, Family, Musical', 'Crime, Drama, Music',
       'Documentary, Drama', 'Animation, Drama, Mystery',
       'Crime, Mystery, Romance', 'Drama, Romance, Sci-Fi',
       'Fantasy, Mystery, Romance', 'Crime, Mystery, Thriller',
       'Drama, Fantasy, Thriller', 'Family, Fantasy, Horror',
       'Animation, Biography, Drama', 'Drama, Sport',
       'Drama, Thriller, War', 'Horror, Music, Thriller',
       'Comedy, Fantasy, Musical', 'Documentary, Drama, History',
       'Documentary, Crime, Sport', 'Comedy, Drama, War',
       'Animation, Action, Crime', 'Action, Drama, Sport',
       'Comedy, Mystery, Romance', 'Documentary, Crime, Drama',
       'Game-Show', 'Animation, Drama, Family', 'Documentary, Adventure',
       'Drama, History, War', 'Action, Fantasy, Horror', 'Drama, Mystery',
       'Action, Drama, War', 'Music', 'Crime, Drama, Western',
       'Action, Biography, Crime', 'Adventure, Drama, Thriller',
       'Sci-Fi, Thriller', 'Fantasy, Horror, Romance',
       'Crime, Drama, Film-Noir', 'Crime, History, Thriller',
       'Drama, History, Western', 'Family, Fantasy',
       'Drama, Romance, Thriller', 'Fantasy, Horror, Sci-Fi',
       'Comedy, Crime, Mystery', 'Adventure, Drama, Sci-Fi',
       'Fantasy, Horror, Mystery', 'Action, War',
       'Comedy, Fantasy, Horror', 'Animation, Action',
       'Short, Drama, Sci-Fi', 'Short, Drama, Romance',
       'Documentary, Drama, Mystery', 'Animation, Drama, Horror',
       'Short, Action, Comedy', 'Animation, Comedy, Family',
       'Comedy, Family, Fantasy', 'Horror, Reality-TV',
       'Adventure, Comedy, Mystery', 'Documentary, Biography, Comedy',
       'Adventure, Romance', 'Crime', 'Animation, Comedy, Sport',
       'Biography, Crime', 'Animation, Adventure, Horror',
       'Action, Drama, Western', 'Documentary, Comedy, History',
       'Animation, Short, Adventure', 'Documentary, Crime, Music',
       'Comedy, Horror, Thriller', 'Romance', 'Action, Fantasy, Western',
       'Documentary, Biography', 'Adventure, Drama, Romance', 'Action',
       'Action, Comedy, Thriller', 'Biography, Drama, Thriller',
       'History, Sport, Thriller', 'Crime, Fantasy, Thriller',
       'Animation, Family', 'Action, Sci-Fi', 'Action, Adventure, War',
       'Family, Game-Show', 'Animation', 'Drama, Musical',
       'Biography, Drama, War', 'Comedy, Romance, Sci-Fi',
       'Documentary, History, War', 'Documentary, History',
       'Comedy, Thriller', 'Action, Fantasy', 'Action, Comedy, History',
       'Drama, Fantasy, Sport', 'Documentary, Reality-TV',
       'Drama, Family, Music', 'Documentary, Comedy', 'Family',
       'Fantasy, Horror', 'Animation, Short, Drama',
       'Animation, Action, Family', 'Comedy, Fantasy, Mystery',
       'Animation, Short, Action', 'Action, Romance, Sci-Fi',
       'Fantasy, Romance', 'Comedy, Drama, Horror', 'Film-Noir, Thriller',
       'Animation, Comedy, Fantasy', 'Sport', 'Romance, Sci-Fi',
       'Documentary, Short, Sport', 'Short, Comedy, Music',
       'Documentary, Biography, Music', 'Drama, Romance, Sport',
       'Animation, Action, Romance', 'Comedy, Horror, Sci-Fi',
       'Family, Sport', 'Biography, Thriller', 'Short, Drama',
       'Comedy, Musical, Romance', 'Documentary, Music',
       'Comedy, Crime, Western', 'Documentary, War',
       'Comedy, Horror, Romance', 'Action, Romance',
       'Action, Mystery, Romance', 'Short, Crime, Drama',
       'Comedy, Music, Romance', 'Action, Drama, Romance',
       'Comedy, Music, Musical', 'Short, Action, Adventure',
       'Documentary, Family', 'Drama, Family, Sci-Fi', 'Biography, Music',
       'Short, Comedy, Crime', 'Music, Romance',
       'Animation, Adventure, Sci-Fi', 'Animation, Action, History',
       'Comedy, Horror, Reality-TV', 'Documentary, Adventure, Game-Show',
       'Talk-Show', 'Animation, Action, Sci-Fi', 'Western',
       'Action, Thriller, War', 'Family, Sci-Fi, Thriller',
       'Comedy, Family, Musical', 'Family, Romance',
       'Action, Adventure, Horror', 'Fantasy, Horror, Thriller',
       'Documentary, Animation', 'Comedy, Talk-Show',
       'Short, Adventure, Comedy', 'Documentary, Short, Sci-Fi',
       'Crime, Film-Noir, Thriller', 'Drama, History, Music',
       'Comedy, News, Talk-Show', 'Drama, Musical, Romance',
       'Crime, Drama, Sci-Fi', 'Crime, Film-Noir, Mystery',
       'Adventure, Family, Sci-Fi', 'Comedy, Drama, Mystery',
       'Game-Show, Horror, Reality-TV', 'Comedy, Horror, Mystery',
       'Action, Comedy, Sci-Fi', 'Adventure, Fantasy, Horror',
       'Short, Horror, Mystery', 'Documentary, Adventure, History',
       'Documentary, Game-Show', 'Adventure, Comedy', 'Comedy, Fantasy',
       'Family, Adventure, Comedy', 'Animation, Family, Musical',
       'Drama, Reality-TV', 'Comedy, Romance, Sport',
       'Documentary, Horror', 'Documentary, Biography, News',
       'Music, Reality-TV', 'Documentary, Short', 'Action, Horror',
       'Comedy, Horror, Talk-Show', 'Adventure, Reality-TV',
       'Animation, Short', 'Family, Music, Romance',
       'Horror, Mystery, Romance', 'Fantasy',
       'Animation, Fantasy, Romance', 'Comedy, Family, Horror',
       'Documentary, Drama, Sport', 'Drama, Film-Noir, Mystery',
       'Documentary, Short, Crime', 'Short, Comedy',
       'Animation, Comedy, Sci-Fi', 'Drama, Horror, Romance',
       'Biography, History, War', 'Documentary, Comedy, Musical',
       'Documentary, Crime, Thriller', 'Documentary, Short, War',
       'Drama, Family, History', 'War', 'Documentary, Romance',
       'Comedy, Romance, Western', 'Documentary, Talk-Show', 'Biography',
       'Documentary, Reality-TV, Sport', 'Action, Mystery',
       'Documentary, Short, Biography', 'Documentary, Animation, Comedy',
       'Adventure', 'Documentary, Biography, Family',
       'Action, Biography, History', 'Documentary, News',
       'Animation, Horror', 'Documentary, History, Sport',
       'Documentary, Mystery', 'Documentary, Comedy, Drama',
       'Animation, Fantasy, Sci-Fi', 'Documentary, Animation, History',
       'Game-Show, Reality-TV, Sport', 'Comedy, History, Romance',
       'Biography, Drama, Mystery', 'Animation, Sport',
       'Drama, Family, Mystery', 'Animation, Fantasy',
       'Documentary, History, News', 'Family, Musical',
       'Animation, Drama, Sport', 'Action, Crime, Romance',
       'Documentary, Horror, Mystery', 'Documentary, Action, Biography',
       'News', 'Horror, Romance', 'Adventure, Family',
       'Documentary, Short, Drama', 'Biography, History',
       'Documentary, Action, History', 'Documentary, Biography, War',
       'Adventure, Music, Sci-Fi', 'Animation, Family, Sci-Fi', 'Musical',
       'Documentary, Drama, Family', 'Comedy, Documentary', 'Short',
       'Documentary, Western', 'Documentary, Short, Family',
       'Documentary, Adventure, Drama', 'Animation, Short, Family',
       'Comedy, Animation', 'Documentary, Biography, Romance',
       'Short, Documentary', 'Documentary, Comedy, Music',
       'Family, Music', 'Action, History', 'Documentary, Short, History',
       'Mystery', 'Documentary, Adventure, News', 'Drama, Short',
       'Action, Adventure, Sport', 'Crime, Horror',
       'Comedy, Drama, History', 'Documentary, Crime, News',
       'Documentary, Music, Sport', 'Documentary, History, Mystery',
       'Documentary, Short, Comedy', 'Mystery, Sci-Fi, Thriller',
       'Documentary, Action, Crime', 'Documentary, Action, Adventure',
       'Game-Show, Music'], dtype=object)

In [ ]:
df.GENRE.nunique()

455